# Generated by Django 3.2.9 on 2022-12-17 16:44

from django.db import migrations, models
import django.db.models.deletion
import tender.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
                ('description', models.TextField()),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TenderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('size', models.CharField(max_length=1024)),
                ('mimetype', models.CharField(max_length=1024)),
                ('file', models.FileField(max_length=2048, upload_to=tender.models.file_location)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.tender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('size', models.CharField(max_length=1024)),
                ('mimetype', models.CharField(max_length=1024)),
                ('file', models.FileField(max_length=2048, upload_to=tender.models.file_location)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.tender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
